<script setup lang="ts">
import type { AccountLifecycle, AccountPolicy } from '~/utils/accountLifecycle'
definePageMeta({ layout: false, darkReady: true })
type Organization = { id: string; name: string; slug: string; account: AccountLifecycle; holdReason: string | null }
const { data, error, refresh, status } = await useFetch<{ policy: AccountPolicy; organizations: Organization[]; deletionEnabled: boolean }>('/api/platform/accounts')
const draft = reactive({ graceDays: data.value?.policy.graceDays ?? 7, retentionDays: data.value?.policy.retentionDays ?? 180, warnings: (data.value?.policy.warningDays ?? [30, 7, 1]).join(', ') })
const selected = ref(''), action = ref('extend'), reason = ref(''), retention = ref(''), exempt = ref(true)
const busy = ref(false), message = ref('')
const simulation = ref<Array<{ id: string; name: string; wouldSuspend: boolean; wouldDelete: boolean; deletionReason: string; account: AccountLifecycle }> | null>(null)
const labels: Record<string, string> = { active: 'Activa', payment_due: 'Pago pendiente', suspended: 'Suspendida', pending_deletion: 'Borrado programado' }
const reasons: Record<string, string> = { payment_due: 'Pago pendiente', canceled: 'Terminó el periodo contratado', trial_ended: 'Terminó la prueba', manual: 'Suspensión manual', deletion_started: 'El borrado definitivo comenzó', deleted: 'Cuenta eliminada', no_administrator: 'No hay un administrador que pueda recibir los avisos', mandatory_notice_pending: 'Falta entregar un aviso obligatorio', notice_period_pending: 'Aún debe cumplirse el plazo del último aviso', cleanup_failed: 'No se pudo completar la limpieza', active_or_exempt: 'Cuenta activa o exenta', retention_pending: 'Conservación pendiente', ready: 'Avisos entregados y conservación cumplida', started: 'Borrado en curso' }
const reasonLabel = (value?: string | null) => value ? reasons[value] ?? 'Requiere revisión del equipo de Flow' : 'Sin suspensión'
const nextAction = (account: AccountLifecycle) => account.exempt ? 'Conservar por exención' : account.reason === 'deletion_started' ? 'Continuar el borrado iniciado' : account.phase === 'payment_due' ? 'Avisar y esperar pago durante la gracia' : ['suspended', 'pending_deletion'].includes(account.phase) ? 'Conservar hasta la fecha prevista; comprobar pago y avisos antes de borrar' : 'Mantener acceso'
const date = (value?: string | null) => value ? new Date(value).toLocaleString('es-MX', { timeZone: 'UTC' }) + ' UTC' : '—'
async function run(fn: () => Promise<unknown>) { busy.value = true; message.value = ''; try { await fn(); await refresh(); message.value = 'Cambios guardados.' } catch { message.value = 'No se pudo completar la acción. Revisa los datos y tus permisos.' } finally { busy.value = false } }
const policy = () => ({ graceDays: Number(draft.graceDays), retentionDays: Number(draft.retentionDays), warningDays: draft.warnings.split(',').map(value => Number(value.trim())) })
async function savePolicy() { await run(() => $fetch('/api/platform/accounts/policy', { method: 'PUT', body: policy() })) }
async function apply() {
  await run(() => $fetch('/api/platform/accounts/action', { method: 'POST', body: { tenantId: selected.value, action: action.value, reason: reason.value, ...(action.value === 'extend' ? { retentionUntil: new Date(retention.value + 'T00:00:00Z').toISOString() } : {}), ...(action.value === 'exempt' ? { exempt: exempt.value } : {}), ...(action.value === 'policy' ? { policy: policy() } : {}) } }))
}
async function simulate() { await run(async () => { const result = await $fetch<{ organizations: NonNullable<typeof simulation.value> }>('/api/platform/accounts/simulation'); simulation.value = result.organizations }) }
</script>
<template>
  <main class="mx-auto min-h-screen max-w-7xl bg-brand-bg px-5 py-8 text-brand-text md:px-10 md:py-12">
    <nav class="mb-8 flex flex-wrap gap-5"><NuxtLink to="/" class="text-brand-navy underline underline-offset-4">Volver a Flow</NuxtLink><NuxtLink to="/platform/plans" class="text-brand-navy underline underline-offset-4">Planes de plataforma</NuxtLink></nav>
    <h1 class="text-3xl font-bold tracking-tight">Ciclo de vida de las cuentas</h1><p class="mt-3 max-w-3xl text-brand-text-secondary">Administra gracia, conservación y excepciones. Las fechas se calculan en UTC. Los planes manuales y la organización de plataforma están exentos.</p>
    <p class="mt-5 rounded-lg border border-brand-border bg-brand-surface p-4 font-medium">Borrado definitivo: {{ data?.deletionEnabled ? 'habilitado en la configuración del servidor' : 'desactivado en la configuración del servidor' }}.</p>
    <p v-if="error" class="mt-5 text-brand-error-text" role="alert">No se pudo cargar el panel. Comprueba tus permisos de plataforma.</p>
    <p v-if="status === 'pending'" class="mt-5" role="status">Cargando cuentas…</p>
    <form class="mt-8 border-b border-brand-border pb-8" @submit.prevent="savePolicy">
      <h2 class="text-xl font-semibold">Plazos globales</h2><div class="mt-4 grid gap-4 md:grid-cols-3">
        <label>Gracia de impago (días)<input v-model.number="draft.graceDays" type="number" min="0" max="90" required></label>
        <label>Retención en suspensión (días)<input v-model.number="draft.retentionDays" type="number" min="31" max="3650" required></label>
        <label>Avisos antes del borrado (días)<input v-model="draft.warnings" required placeholder="30, 7, 1"></label>
      </div><p class="mt-3 text-sm text-brand-text-secondary">Los avisos deben ser distintos y anteriores a la retención. Cambiar estos plazos recalcula las fechas; un aviso tardío pospone el borrado hasta cumplir su plazo.</p><button :disabled="busy" class="primary mt-4">Guardar plazos globales</button>
    </form>
    <section class="mt-8"><div class="flex flex-wrap items-center justify-between gap-4"><h2 class="text-xl font-semibold">Organizaciones</h2><button :disabled="busy" @click="refresh()">Actualizar cuentas</button></div>
      <p v-if="!data?.organizations.length && !error && status !== 'pending'" class="mt-4 text-brand-text-secondary">No hay organizaciones para mostrar.</p>
      <ul class="mt-4 divide-y divide-brand-border"><li v-for="org in data?.organizations" :key="org.id" class="grid gap-3 py-5 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
        <div><h3 class="break-words font-semibold">{{ org.name }}</h3><p class="mt-1 text-brand-text-secondary">{{ labels[org.account.phase] }}{{ org.account.exempt ? ' · Exenta' : '' }}</p></div>
        <dl class="grid gap-2 text-sm"><div><dt class="inline text-brand-text-secondary">Motivo: </dt><dd class="inline">{{ reasonLabel(org.account.reason) }}</dd></div><div><dt class="inline text-brand-text-secondary">Próxima acción: </dt><dd class="inline">{{ nextAction(org.account) }}</dd></div><div><dt class="inline text-brand-text-secondary">Suspensión: </dt><dd class="inline">{{ date(org.account.suspendAt) }}</dd></div><div><dt class="inline text-brand-text-secondary">Borrado previsto: </dt><dd class="inline">{{ date(org.account.deleteAt) }}</dd></div><div v-if="org.holdReason"><dt class="inline text-brand-error-text">Borrado pospuesto: </dt><dd class="inline">{{ reasonLabel(org.holdReason) }}. Revisa los avisos y la limpieza antes de continuar.</dd></div></dl>
      </li></ul>
    </section>
    <form class="mt-8 border-t border-brand-border pt-8" @submit.prevent="apply">
      <h2 class="text-xl font-semibold">Excepción o acción manual</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label>Organización<select v-model="selected" required><option value="" disabled>Selecciona una organización</option><option v-for="org in data?.organizations" :key="org.id" :value="org.id">{{ org.name }}</option></select></label><label>Acción<select v-model="action"><option value="extend">Extender retención</option><option value="policy">Aplicar estos plazos solo a esta cuenta</option><option value="exempt">Cambiar exención</option><option value="suspend">Suspender manualmente</option><option value="reactivate">Reactivar con exención</option><option value="cancel_deletion">Cancelar borrado con exención</option></select></label><label v-if="action === 'extend'">Conservar hasta (UTC)<input v-model="retention" type="date" required></label><label v-if="action === 'exempt'" class="flex items-center gap-3"><input v-model="exempt" type="checkbox">Eximir de suspensión y borrado</label><label class="md:col-span-2">Motivo de la acción<input v-model="reason" minlength="3" maxlength="500" required></label></div>
      <p class="mt-3 text-sm text-brand-text-secondary">Reactivar o cancelar un borrado crea una exención explícita, sin simular un cobro. La suspensión manual se aplica al guardar. Una cuenta cuyo borrado ya comenzó requiere revisión del equipo de Flow.</p><button class="primary mt-4" :disabled="busy || !selected">Aplicar acción</button>
    </form>
    <section class="mt-8 border-t border-brand-border pt-8"><h2 class="text-xl font-semibold">Simulación</h2><p class="mt-2 text-brand-text-secondary">Consulta las etapas actuales y las cuentas elegibles para borrar, incluidos los avisos pendientes. Esta consulta no modifica datos.</p><button class="mt-4" :disabled="busy" @click="simulate">Consultar simulación</button><ul v-if="simulation" class="mt-4 divide-y divide-brand-border"><li v-for="org in simulation" :key="org.id" class="py-3 break-words"><strong>{{ org.name }}</strong>: {{ org.wouldDelete ? 'Elegible para borrado' : org.wouldSuspend ? 'Suspendida; conservación pendiente o bloqueada' : 'Con acceso' }} · {{ reasonLabel(org.deletionReason) }}<p class="mt-1 text-sm text-brand-text-secondary">Suspensión: {{ date(org.account.suspendAt) }} · Borrado previsto: {{ date(org.account.deleteAt) }}</p></li></ul></section>
    <p class="mt-5 text-brand-text-secondary" role="status">{{ message }}</p>
  </main>
</template>
<style scoped>label{display:block;font-size:.875rem}input:not([type=checkbox]),select{display:block;width:100%;margin-top:.5rem;padding:.65rem .75rem;border:1px solid rgb(var(--brand-border));border-radius:.5rem;background:rgb(var(--brand-surface));color:rgb(var(--brand-text))}button{padding:.65rem 1rem;border:1px solid rgb(var(--brand-border));border-radius:.5rem;background:rgb(var(--brand-surface));color:rgb(var(--brand-text));font-weight:600;cursor:pointer}button.primary{background:rgb(var(--brand-navy));color:rgb(var(--brand-primary-fg))}button:disabled{opacity:.5;cursor:wait}button:hover{filter:brightness(.96)}input:focus-visible,select:focus-visible,button:focus-visible,a:focus-visible{outline:2px solid rgb(var(--brand-blue));outline-offset:3px}</style>
