/** HU-ERD-161: los valores claros conservan la paleta original. */
export const lightTokens = {
  bg: '#F5F8FA', surface: '#FFFFFF', border: '#CBD6E2', 'border-light': '#E5EAF0',
  text: '#33475B', 'text-secondary': '#516F90', 'text-muted': '#8DA1B5',
  orange: '#FF7A59', 'orange-hover': '#E66E50', blue: '#0091AE', 'blue-bg': '#EAF3F6',
  navy: '#213343', 'sidebar-active-bg': '#EAF0F6',
  'success-bg': '#CCF1DE', 'success-text': '#0A7A4F', 'warning-bg': '#FEF0D2', 'warning-text': '#B3720A',
  'error-bg': '#FBE0DD', 'error-text': '#C7391F', 'info-bg': '#E5F5F8', 'info-text': '#0091AE',
  'neutral-bg': '#EAF0F6', 'neutral-text': '#516F90', 'purple-bg': '#EDE7FB', 'purple-text': '#6D3FC4',
  'pink-bg': '#FCE4EF', 'pink-text': '#C42B7A', 'gold-bg': '#FBF3D9', 'gold-text': '#8C6D14',
  'indigo-bg': '#E0E7FF', 'indigo-text': '#4338CA',
  'primary-fg': '#FFFFFF', 'accent-fg': '#FFFFFF', 'error-fg': '#FFFFFF',
  'control-border': '#CBD6E2', 'switch-thumb': '#FFFFFF',
  'panel-soft': '#FDFEFE', 'panel-border': '#D9E2EB', 'panel-muted': '#718096',
  'help-bg': '#EAF7F9', 'help-hover': '#D9F0F4', 'help-border': '#B9DCE4', 'help-text': '#006E84',
  'message-border': '#CDEBF0', 'message-text': '#214E59', 'panel-hover': '#EDF3F6',
  'dashboard-soft': '#F8FAFC', 'blue-hover': '#007F98', 'shortcut-border': '#9FCBD5',
  'shortcut-arrow': '#B1BFCC', 'table-divider': '#E5E7EB', 'scrollbar': '#CBD5E1',
  'usage-warning': '#985E08', 'usage-link': '#007C95', 'tooltip-muted': '#D7E0E8', 'tooltip-link': '#7FD8EE',
  'body-bg': '#F9FAFB', 'body-text': '#111827', 'spinner-track': '#CFE4E9',
  'skeleton-base': '#EDF1F4', 'skeleton-highlight': '#F7F9FA', 'dashboard-focus': '#71BDCD',
  'dashboard-error-border': '#EFB8B0', 'dashboard-error-hover': '#A9321C', 'filter-hover': '#DCECF1',
  'tooltip-bg': '#33475B', 'tooltip-fg': '#FFFFFF', 'overlay': '#213343', 'shadow': '#33475B',
  'kanban-column': '#EEF2F7', 'kanban-focus': '#8FC8D4', 'kanban-divider': '#EDF1F5',
  'stage-cyan': '#00A4BD', 'stage-purple': '#6A5ACD', 'mention-hover': '#007A91',
  'activity-error': '#B42318', 'origin-border': '#DBE8EC', 'origin-bg': '#F5FAFB',
  'app-pending-text': '#B45309', 'app-pending-dot': '#D97706', 'modal-overlay': '#000000',
  'settings-overlay': '#1D2939', 'settings-dialog-overlay': '#1D293B', 'billing-divider': '#EEF2F6',
  'billing-warning-fill': '#D99A16', 'billing-critical-fill': '#E05B43',
  'billing-sites': '#36B9D1', 'billing-docs': '#9BDDED', 'billing-history': '#DFE8EF',
  'billing-warning-border': '#F4D58D', 'billing-warning-bg': '#FFF4D6', 'billing-warning-text': '#805800',
  'billing-error-border': '#F0B7AD', 'billing-error-bg': '#FDE7E3', 'billing-error-text': '#A83420',
  'billing-info-border': '#BEE4EC', 'billing-info-bg': '#EAF7FA', 'billing-info-text': '#086F83',
  'recipient-text': '#006F86', 'recipient-role': '#6534B0',
  'module-code-bg': '#172B4D', 'module-code-text': '#D9E7F5',
  'chat-own-border': '#B7E7EF', 'chat-warning-bg': '#FFF4E5',
  'chat-warning-text': '#8A5D00', 'chat-warning-border': '#C58B2A',
  'label-muted': '#8BA0B5', 'label-heading': '#16324F', 'label-toggle-bg': '#B9C7D3',
  'label-toggle-active': '#FF765B', 'label-label': '#38536E', 'label-control-border': '#CBD9E5',
  'label-control-text': '#334E68', 'label-focus': '#0097B2', 'label-divider': '#E6EDF3',
  'label-section': '#294866', 'label-secondary': '#52718F', 'label-selected-bg': '#E7F5F7',
  'label-selected-text': '#007F99', 'label-icon': '#5D7993', 'label-stage': '#F1F6F8',
  'label-paper-border': '#BCCBD7', 'label-ink': '#183651', 'label-shadow': '#183651',
  'label-paper-muted': '#66829D', 'label-paper-separator': '#B5C2CC',
  // HU-165: colores claros exactos del diseñador y de vue-flow.
  'designer-selected-edge': '#C94F19',
  'designer-system-muted': '#64748B',
  'designer-new-arrow': '#F97316',
  'designer-existing-edge': '#94A3B8',
  'designer-new': '#E8682D',
  'designer-edge': '#8B9BAC',
  'designer-label': '#526579',
  'designer-minimap-existing': '#9DAAB7',
  'designer-grid-minor': '#E9EFF3',
  'designer-grid-major': '#DFE8EE',
  'designer-section-bg': '#F8FAFB',
  'designer-section-text': '#657789',
  'designer-system-text': '#334155',
  'designer-related': '#D65A23',
  'designer-system-tag': '#E2E8F0',
  'designer-node-border': '#AEBDC9',
  'designer-node-text': '#243849',
  'designer-node-head': '#F4F7F9',
  'designer-new-head': '#FFF3EF',
  'designer-node-meta': '#708191',
  'designer-added-row': '#E7F6FA',
  'designer-added-bg': '#D2EEF5',
  'designer-added-text': '#087A96',
  'designer-node-divider': '#E1E7EB',
  'designer-inspector-divider': '#DCE5EB',
  'designer-markdown-heading': '#253044',
  'designer-markdown-code': '#F1F4F8',
  'designer-markdown-border': '#DBE2EA',
  'designer-existing': '#CBD5E1',
  'designer-error-border': '#FECACA',
  'designer-error-bg': '#FEF2F2',
  'designer-error-text': '#991B1B',
  'designer-error-action': '#B91C1C',
  'designer-error-control': '#FCA5A5',
  'designer-error-hover': '#FEE2E2',
  'designer-success-border': '#BBF7D0',
  'designer-success-bg': '#F0FDF4',
  'designer-success-text': '#166534',
  'designer-success-strong': '#14532D',
  'designer-warning-border': '#FDE68A',
  'designer-warning-bg': '#FFFBEB',
  'designer-warning-text': '#451A03',
  'designer-warning-secondary': '#92400E',
  'designer-warning-strong': '#78350F',
  'designer-warning-link': '#B45309',
  'designer-review-overlay': '#0F172A',
  'designer-controls-bg': '#FEFEFE',
  'designer-controls-border': '#EEEEEE',
  'designer-controls-hover': '#F4F4F4',
  'designer-controls-icon': '#000000',
  'designer-minimap-mask': '#F0F0F0',
  'designer-selection': '#0059DC',
  'designer-connection': '#B1B1B7',
  'designer-handle': '#555555',
  'designer-system-icon': '#475569',
  'designer-type': '#8DA1B5',
  'designer-edge-updating': '#777777'
} as const

export const darkTokens: Record<keyof typeof lightTokens, string> = {
  bg: '#141B29', surface: '#1E2A3D', border: '#3A4A5E', 'border-light': '#2C374A',
  text: '#F0F4F8', 'text-secondary': '#9FB3C8', 'text-muted': '#7A8CA0',
  orange: '#FF8F6B', 'orange-hover': '#FFA184', blue: '#3FC3DE', 'blue-bg': '#0F3A44',
  navy: '#F0F4F8', 'sidebar-active-bg': '#2A3648',
  'success-bg': '#123D2A', 'success-text': '#4ADE94', 'warning-bg': '#402D0A', 'warning-text': '#F5B94D',
  'error-bg': '#3D1712', 'error-text': '#FF8A76', 'info-bg': '#0F2E36', 'info-text': '#4DD0E1',
  'neutral-bg': '#2A3648', 'neutral-text': '#AEC0D2', 'purple-bg': '#2A2140', 'purple-text': '#C4A7FF',
  'pink-bg': '#3A1F2C', 'pink-text': '#FF9CCC', 'gold-bg': '#352C16', 'gold-text': '#E8CB73',
  'indigo-bg': '#252B4B', 'indigo-text': '#B7BFFF',
  'primary-fg': '#1A2233', 'accent-fg': '#1A2233', 'error-fg': '#1A2233',
  'control-border': '#7A8CA0', 'switch-thumb': '#FFFFFF',
  'panel-soft': '#1E2A3D', 'panel-border': '#3A4A5E', 'panel-muted': '#9FB3C8',
  'help-bg': '#0F3A44', 'help-hover': '#174853', 'help-border': '#3FC3DE', 'help-text': '#4DD0E1',
  'message-border': '#3A4A5E', 'message-text': '#AEC0D2', 'panel-hover': '#2A3648',
  'dashboard-soft': '#141B29', 'blue-hover': '#4DD0E1', 'shortcut-border': '#3FC3DE',
  'shortcut-arrow': '#9FB3C8', 'table-divider': '#3A4A5E', 'scrollbar': '#3A4A5E',
  'usage-warning': '#F5B94D', 'usage-link': '#3FC3DE', 'tooltip-muted': '#9FB3C8', 'tooltip-link': '#3FC3DE',
  'body-bg': '#141B29', 'body-text': '#F0F4F8', 'spinner-track': '#3A4A5E',
  'skeleton-base': '#2C374A', 'skeleton-highlight': '#3A4A5E', 'dashboard-focus': '#3FC3DE',
  'dashboard-error-border': '#FF8A76', 'dashboard-error-hover': '#FFA99A', 'filter-hover': '#174853',
  'tooltip-bg': '#1E2A3D', 'tooltip-fg': '#F0F4F8', 'overlay': '#000000', 'shadow': '#000000',
  'kanban-column': '#141B29', 'kanban-focus': '#3FC3DE', 'kanban-divider': '#2C374A',
  'stage-cyan': '#4DD0E1', 'stage-purple': '#C4A7FF', 'mention-hover': '#4DD0E1',
  'activity-error': '#FF8A76', 'origin-border': '#3A4A5E', 'origin-bg': '#141B29',
  'app-pending-text': '#F5B94D', 'app-pending-dot': '#F5B94D', 'modal-overlay': '#000000',
  // HU-163: derivados de roles existentes; los claros son los literales originales de ajustes.
  'settings-overlay': '#000000', 'settings-dialog-overlay': '#000000', 'billing-divider': '#2C374A',
  'billing-warning-fill': '#F5B94D', 'billing-critical-fill': '#FF8A76',
  'billing-sites': '#4DD0E1', 'billing-docs': '#9BDDED', 'billing-history': '#3A4A5E',
  'billing-warning-border': '#F5B94D', 'billing-warning-bg': '#402D0A', 'billing-warning-text': '#F5B94D',
  'billing-error-border': '#FF8A76', 'billing-error-bg': '#3D1712', 'billing-error-text': '#FF8A76',
  'billing-info-border': '#3FC3DE', 'billing-info-bg': '#0F2E36', 'billing-info-text': '#4DD0E1',
  // HU-164: claros originales de destinatarios, ejemplo API y estados del chat.
  'recipient-text': '#4DD0E1', 'recipient-role': '#C4A7FF',
  'module-code-bg': '#141B29', 'module-code-text': '#F0F4F8',
  'chat-own-border': '#3FC3DE', 'chat-warning-bg': '#402D0A',
  'chat-warning-text': '#F5B94D', 'chat-warning-border': '#F5B94D',
  // HU-164: claros exactos del editor; déficits claros heredados autorizados y auditados aparte.
  'label-muted': '#9FB3C8', 'label-heading': '#F0F4F8', 'label-toggle-bg': '#7A8CA0',
  'label-toggle-active': '#FF8F6B', 'label-label': '#9FB3C8', 'label-control-border': '#7A8CA0',
  'label-control-text': '#F0F4F8', 'label-focus': '#3FC3DE', 'label-divider': '#2C374A',
  'label-section': '#F0F4F8', 'label-secondary': '#9FB3C8', 'label-selected-bg': '#0F3A44',
  'label-selected-text': '#4DD0E1', 'label-icon': '#9FB3C8', 'label-stage': '#141B29',
  'label-paper-border': '#3A4A5E', 'label-ink': '#F0F4F8', 'label-shadow': '#000000',
  'label-paper-muted': '#9FB3C8', 'label-paper-separator': '#9FB3C8',
  // Oscuros derivados de los roles congelados; déficits claros heredados autorizados aparte.
  'designer-selected-edge': '#FFA184',
  'designer-system-muted': '#9FB3C8',
  'designer-new-arrow': '#FF8F6B',
  'designer-existing-edge': '#9FB3C8',
  'designer-new': '#FF8F6B',
  'designer-edge': '#9FB3C8',
  'designer-label': '#9FB3C8',
  'designer-minimap-existing': '#9FB3C8',
  'designer-grid-minor': '#202C3D',
  'designer-grid-major': '#2C374A',
  'designer-section-bg': '#141B29',
  'designer-section-text': '#9FB3C8',
  'designer-system-text': '#F0F4F8',
  'designer-related': '#FFA184',
  'designer-system-tag': '#2A3648',
  'designer-node-border': '#7A8CA0',
  'designer-node-text': '#F0F4F8',
  'designer-node-head': '#243247',
  'designer-new-head': '#40291F',
  'designer-node-meta': '#AEC0D2',
  'designer-added-row': '#0F3A44',
  'designer-added-bg': '#174853',
  'designer-added-text': '#4DD0E1',
  'designer-node-divider': '#2C374A',
  'designer-inspector-divider': '#2C374A',
  'designer-markdown-heading': '#F0F4F8',
  'designer-markdown-code': '#141B29',
  'designer-markdown-border': '#3A4A5E',
  'designer-existing': '#9FB3C8',
  'designer-error-border': '#FF8A76',
  'designer-error-bg': '#3D1712',
  'designer-error-text': '#FF8A76',
  'designer-error-action': '#FF8A76',
  'designer-error-control': '#FF8A76',
  'designer-error-hover': '#4C2019',
  'designer-success-border': '#4ADE94',
  'designer-success-bg': '#123D2A',
  'designer-success-text': '#4ADE94',
  'designer-success-strong': '#4ADE94',
  'designer-warning-border': '#F5B94D',
  'designer-warning-bg': '#402D0A',
  'designer-warning-text': '#F5B94D',
  'designer-warning-secondary': '#F5B94D',
  'designer-warning-strong': '#F5B94D',
  'designer-warning-link': '#F5B94D',
  'designer-review-overlay': '#000000',
  'designer-controls-bg': '#1E2A3D',
  'designer-controls-border': '#2C374A',
  'designer-controls-hover': '#2A3648',
  'designer-controls-icon': '#F0F4F8',
  'designer-minimap-mask': '#141B29',
  'designer-selection': '#3FC3DE',
  'designer-connection': '#9FB3C8',
  'designer-handle': '#9FB3C8',
  'designer-system-icon': '#9FB3C8',
  'designer-type': '#9FB3C8',
  'designer-edge-updating': '#9FB3C8'
}

export function rgbChannels(hex: string): string {
  return [1, 3, 5].map(start => parseInt(hex.slice(start, start + 2), 16)).join(' ')
}

export const brandColors = Object.fromEntries(Object.keys(lightTokens).map(name => [name, `rgb(var(--brand-${name}) / <alpha-value>)`]))
