// Pedido directo del usuario (2026-09-01): primero un selector curado de 24
// iconos; el mismo dia, feedback directo del usuario sobre ese primer
// selector - "cuando decia selector de iconos me imaginaba que me darias un
// componente como el que tienes ya creado pero con todos los iconos y un
// buscador" - se reemplaza el whitelist curado por el catalogo COMPLETO de
// @lucide/vue (1781 iconos, un nombre canonico PascalCase por glifo unico,
// sin contar los alias como "UsersIcon"/"LucideUsers" que exporta el paquete
// para el mismo icono).
//
// Archivo de datos puro (sin import de Vue/lucide-vue) para poder usarse
// desde Nitro server-side sin arrastrar el runtime de componentes - mismo
// criterio que la version anterior de este archivo. La lista se genero una
// sola vez a partir de node_modules/@lucide/vue/dist/esm/icons/index.mjs
// (export canonico, un nombre por archivo/icono) y se congela aca; no se
// deriva en runtime porque node_modules no es una fuente estable para
// validar requests HTTP.
//
// MODULE_ICON_KEYS ya NO es un union type literal (evita una union de 1781
// miembros, lento de chequear en TS) - es un readonly string[] comun,
// validado en runtime via MODULE_ICON_KEY_SET (ver server/api/entities/index.post.ts
// y [id].put.ts, que usan z.string().refine() en vez de z.enum()).
export const MODULE_ICON_KEYS: readonly string[] = [
  'AArrowDown', 'AArrowUp', 'ALargeSmall', 'Accessibility', 'Activity', 'Ad', 'AirVent', 'Airplay',
  'AlarmClockMinus', 'AlarmClockCheck', 'AlarmClockOff', 'AlarmClockPlus', 'AlarmClock', 'AlarmSmoke', 'Album', 'AlignCenterHorizontal',
  'AlignCenterVertical', 'AlignEndHorizontal', 'AlignEndVertical', 'AlignHorizontalDistributeCenter', 'AlignHorizontalDistributeEnd', 'AlignHorizontalDistributeStart', 'AlignHorizontalJustifyCenter', 'AlignHorizontalJustifyEnd',
  'AlignHorizontalJustifyStart', 'AlignHorizontalSpaceAround', 'AlignHorizontalSpaceBetween', 'AlignStartHorizontal', 'AlignStartVertical', 'AlignVerticalDistributeCenter', 'AlignVerticalDistributeEnd', 'AlignVerticalDistributeStart',
  'AlignVerticalJustifyCenter', 'AlignVerticalJustifyEnd', 'AlignVerticalJustifyStart', 'AlignVerticalSpaceAround', 'AlignVerticalSpaceBetween', 'Ambulance', 'Ampersand', 'Ampersands',
  'Amphora', 'Angle', 'Anchor', 'Antenna', 'Anvil', 'Aperture', 'AppWindowMac', 'AppWindow',
  'Apple', 'ArchiveRestore', 'ArchiveX', 'Archive', 'Armchair', 'ArrowBigDownDash', 'ArrowBigDown', 'ArrowBigLeftDash',
  'ArrowBigLeft', 'ArrowBigRightDash', 'ArrowBigRight', 'ArrowBigUpDash', 'ArrowBigUp', 'ArrowDown01', 'ArrowDown10', 'ArrowDownAZ',
  'ArrowDownLeft', 'ArrowDownFromLine', 'ArrowDownNarrowWide', 'ArrowDownRight', 'ArrowDownToDot', 'ArrowDownToLine', 'ArrowDownUp', 'ArrowDownWideNarrow',
  'ArrowDownZA', 'ArrowDown', 'ArrowLeftFromLine', 'ArrowLeftRight', 'ArrowLeftToLine', 'ArrowLeft', 'ArrowRightFromLine', 'ArrowRightToLine',
  'ArrowRightLeft', 'ArrowRight', 'ArrowUp01', 'ArrowUp10', 'ArrowUpAZ', 'ArrowUpDown', 'ArrowUpFromDot', 'ArrowUpFromLine',
  'ArrowUpLeft', 'ArrowUpRight', 'ArrowUpNarrowWide', 'ArrowUpToLine', 'ArrowUpZA', 'ArrowUpWideNarrow', 'ArrowUp', 'ArrowsUpFromLine',
  'Astroid', 'Asterisk', 'AtSign', 'Atom', 'AudioLinesOff', 'AudioLinesX', 'AudioWaveform', 'Award',
  'AudioLines', 'Axe', 'Axis3d', 'Baby', 'Backpack', 'BadgeAlert', 'BadgeCent', 'BadgeCheck',
  'BadgeDollarSign', 'BadgeEuro', 'BadgeIndianRupee', 'BadgeInfo', 'BadgeJapaneseYen', 'BadgePercent', 'BadgePlus', 'BadgeMinus',
  'BadgePoundSterling', 'BadgeQuestionMark', 'BadgeRussianRuble', 'BadgeSwissFranc', 'BadgeTurkishLira', 'Badge', 'BadgeX', 'BaggageClaim',
  'Balloon', 'Ban', 'Banana', 'Bandage', 'BanknoteArrowDown', 'BanknoteCheck', 'BanknoteX', 'BanknoteArrowUp',
  'Banknote', 'Barcode', 'Barrel', 'Baseline', 'Bath', 'BatteryCharging', 'BatteryLow', 'BatteryFull',
  'BatteryMedium', 'BatteryPlus', 'BatteryWarning', 'Battery', 'Beaker', 'BeanOff', 'Bean', 'BedDouble',
  'BedSingle', 'Bed', 'BeefOff', 'Beef', 'Beer', 'BeerOff', 'BellCheck', 'BellElectric',
  'BellDot', 'BellMinus', 'BellOff', 'BellRing', 'BellPlus', 'Bell', 'BetweenHorizontalEnd', 'BetweenHorizontalStart',
  'BetweenVerticalEnd', 'BetweenVerticalStart', 'BicepsFlexed', 'Bike', 'Binary', 'Binoculars', 'Biohazard', 'Bird',
  'Birdhouse', 'Bitcoin', 'Blend', 'Blender', 'Blinds', 'Blocks', 'BluetoothOff', 'BluetoothConnected',
  'BluetoothSearching', 'Bluetooth', 'Bold', 'Bomb', 'Bolt', 'BoneFracture', 'Bone', 'BookA',
  'BookAlert', 'BookAudio', 'BookCheck', 'BookCopy', 'BookDashed', 'BookDown', 'BookHeadphones', 'BookHeart',
  'BookImage', 'BookKey', 'BookMarked', 'BookLock', 'BookMinus', 'BookOpenCheck', 'BookOpenText', 'BookOpen',
  'BookPlus', 'BookText', 'BookSearch', 'BookType', 'BookUp2', 'BookUp', 'BookUser', 'BookX',
  'Book', 'BookmarkCheck', 'BookmarkMinus', 'BookmarkOff', 'BookmarkPlus', 'BookmarkX', 'Bookmark', 'BoomBox',
  'BotMessageSquare', 'BotOff', 'Bot', 'BottleWine', 'BowArrow', 'Box', 'Boxes', 'Braces',
  'Brackets', 'BrainCog', 'BrainCircuit', 'Brain', 'BrickWallFire', 'BrickWallShield', 'BrickWall', 'BriefcaseConveyorBelt',
  'BriefcaseBusiness', 'BriefcaseMedical', 'Briefcase', 'BringToFront', 'Broccoli', 'BroomSparkles', 'Broom', 'BrushCleaning',
  'Brush', 'Bubbles', 'BugOff', 'BugPlay', 'Bug', 'Building', 'Building2', 'BusFront',
  'Bus', 'CableCar', 'Cable', 'CakeSlice', 'Cake', 'Calculator', 'Calendar1', 'CalendarArrowDown',
  'CalendarArrowUp', 'CalendarCheck2', 'CalendarCheck', 'CalendarClock', 'CalendarCog', 'CalendarDays', 'CalendarFold', 'CalendarMinus2',
  'CalendarHeart', 'CalendarMinus', 'CalendarOff', 'CalendarPlus2', 'CalendarPlus', 'CalendarRange', 'CalendarSearch', 'CalendarSync',
  'CalendarX2', 'CalendarX', 'Calendar', 'Calendars', 'CameraOff', 'Camera', 'CandyCane', 'CandyOff',
  'Candy', 'CannabisOff', 'Cannabis', 'CaptionsOff', 'Captions', 'CarBattery', 'CarFront', 'CarTaxiFront',
  'Car', 'Caravan', 'CardSim', 'Carrot', 'CaseLower', 'CaseSensitive', 'CaseUpper', 'CassetteTape',
  'Cast', 'Castle', 'Cat', 'CctvOff', 'Cctv', 'ChartArea', 'ChartBarBig', 'ChartBarIncreasing',
  'ChartBarDecreasing', 'ChartBarStacked', 'ChartBar', 'ChartColumnBig', 'ChartColumnDecreasing', 'ChartCandlestick', 'ChartColumnIncreasing', 'ChartColumnStacked',
  'ChartColumn', 'ChartGantt', 'ChartLine', 'ChartNetwork', 'ChartNoAxesColumnDecreasing', 'ChartNoAxesColumnIncreasing', 'ChartNoAxesColumn', 'ChartNoAxesCombined',
  'ChartNoAxesGantt', 'ChartPie', 'ChartScatter', 'ChartSpline', 'CheckCheck', 'CheckLine', 'Check', 'ChefHat',
  'Cherry', 'ChessKing', 'ChessBishop', 'ChessKnight', 'ChessPawn', 'ChessQueen', 'ChessRook', 'ChevronDown',
  'ChevronFirst', 'ChevronLast', 'ChevronLeft', 'ChevronRight', 'ChevronUp', 'ChevronsDownUp', 'ChevronsDown', 'ChevronsLeftRightEllipsis',
  'ChevronsLeftRight', 'ChevronsLeft', 'ChevronsRightLeft', 'ChevronsRight', 'ChevronsUpDown', 'ChevronsUp', 'CigaretteOff', 'Church',
  'Cigarette', 'CircleAlert', 'CircleArrowDown', 'CircleArrowLeft', 'CircleArrowOutDownLeft', 'CircleArrowOutDownRight', 'CircleArrowOutUpLeft', 'CircleArrowOutUpRight',
  'CircleArrowRight', 'CircleArrowUp', 'CircleCheckBig', 'CircleCheck', 'CircleChevronDown', 'CircleChevronLeft', 'CircleChevronRight', 'CircleChevronUp',
  'CircleDivide', 'CircleDashed', 'CircleDollarSign', 'CircleDot', 'CircleDotDashed', 'CircleEllipsis', 'CircleEqual', 'CircleEuro',
  'CircleFadingArrowUp', 'CircleFadingPlus', 'CircleMinus', 'CircleGauge', 'CircleOff', 'CircleParking', 'CircleParkingOff', 'CirclePause',
  'CirclePercent', 'CirclePile', 'CirclePlay', 'CirclePlus', 'CirclePoundSterling', 'CirclePower', 'CircleSlash2', 'CircleQuestionMark',
  'CircleSlash', 'CircleSmall', 'CircleStar', 'CircleStop', 'CircleUserRound', 'CircleUser', 'CircleX', 'Circle',
  'CircuitBoard', 'Citrus', 'Clapperboard', 'ClipboardCheck', 'ClipboardClock', 'ClipboardCopy', 'ClipboardList', 'ClipboardMinus',
  'ClipboardPaste', 'ClipboardPenLine', 'ClipboardPen', 'ClipboardPlus', 'ClipboardType', 'ClipboardX', 'Clipboard', 'Clock1',
  'Clock10', 'Clock11', 'Clock12', 'Clock2', 'Clock3', 'Clock4', 'Clock5', 'Clock6',
  'Clock7', 'Clock8', 'Clock9', 'ClockAlert', 'ClockArrowDown', 'ClockArrowLeft', 'ClockArrowRight', 'ClockArrowUp',
  'ClockCheck', 'ClockFading', 'ClockPlus', 'Clock', 'ClosedCaption', 'CloudAlert', 'CloudBackup', 'CloudCheck',
  'CloudCog', 'CloudDownload', 'CloudDrizzle', 'CloudFog', 'CloudHail', 'CloudLightning', 'CloudMoonRain', 'CloudMoon',
  'CloudOff', 'CloudRainWind', 'CloudSnow', 'CloudRain', 'CloudSunRain', 'CloudSun', 'CloudUpload', 'CloudSync',
  'Cloud', 'Clover', 'Cloudy', 'CodeXml', 'Club', 'Code', 'Coffee', 'Cog',
  'Coins', 'Columns2', 'Columns3Cog', 'Columns3', 'Columns4', 'Command', 'Combine', 'Compass',
  'Component', 'Computer', 'ConciergeBell', 'Cone', 'Construction', 'Container', 'ContactRound', 'Contact',
  'Contrast', 'Cookie', 'CookingPot', 'CopyCheck', 'CopyMinus', 'CopySlash', 'CopyPlus', 'CopyX',
  'Copy', 'Copyleft', 'Copyright', 'CornerDownLeft', 'CornerDownRight', 'CornerLeftDown', 'CornerLeftUp', 'CornerRightDown',
  'CornerRightUp', 'CornerUpLeft', 'CornerUpRight', 'Cpu', 'CreativeCommons', 'CreditCard', 'Croissant', 'Crop',
  'Cross', 'Crown', 'Crosshair', 'Cuboid', 'CupSoda', 'Currency', 'Cylinder', 'Dam',
  'DatabaseArrowDown', 'DatabaseArrowUp', 'DatabaseBackup', 'DatabaseCheck', 'DatabasePlus', 'DatabaseMinus', 'DatabaseSearch', 'DatabaseX',
  'DatabaseZap', 'Database', 'DecimalsArrowLeft', 'Delete', 'DecimalsArrowRight', 'Dessert', 'Diameter', 'DiamondMinus',
  'DiamondPercent', 'DiamondPlus', 'Diamond', 'Dice1', 'Dice2', 'Dice3', 'Dice4', 'Dice5',
  'Dice6', 'Dices', 'Diff', 'Disc2', 'Disc3', 'DiscAlbum', 'Disc', 'Divide',
  'DnaOff', 'Dna', 'Dog', 'Dock', 'DollarSign', 'Donut', 'DoorClosed', 'DoorClosedLocked',
  'DoorOpen', 'Dot', 'Download', 'DraftingCompass', 'Drama', 'Drill', 'Drone', 'DropletOff',
  'Droplet', 'Droplets', 'Drum', 'Drumstick', 'Dumbbell', 'EarOff', 'Ear', 'EarthLock',
  'Eclipse', 'EggFried', 'Earth', 'EggOff', 'Egg', 'Eject', 'Ellipse', 'EllipsisVertical',
  'Ellipsis', 'EqualApproximately', 'EqualNot', 'Equal', 'Eraser', 'EthernetPort', 'Euro', 'EvCharger',
  'Expand', 'ExternalLink', 'EyeClosed', 'EyeDashed', 'EyeOff', 'Eye', 'FaceAngry', 'FaceGrinning',
  'FaceExpressionless', 'FaceNeutral', 'FaceSlightlyFrowning', 'FaceSlightlySmilingPlus', 'FaceSlightlySmiling', 'Factory', 'Fan', 'FastForward',
  'Feather', 'Fence', 'FerrisWheel', 'FileArchive', 'FileBadge', 'FileAxis3d', 'FileBox', 'FileBracesCorner',
  'FileBraces', 'FileChartColumnIncreasing', 'FileChartColumn', 'FileChartLine', 'FileChartPie', 'FileCheckCorner', 'FileCheck', 'FileClock',
  'FileCodeCorner', 'FileCode', 'FileCog', 'FileDiff', 'FileDown', 'FileDigit', 'FileExclamationPoint', 'FileHeadphone',
  'FileHeart', 'FileInput', 'FileImage', 'FileKey', 'FileLock', 'FileMinusCorner', 'FileMinus', 'FileMusic',
  'FileOutput', 'FilePenLine', 'FilePen', 'FilePlay', 'FilePlusCorner', 'FilePlus', 'FileQuestionMark', 'FileSearchCorner',
  'FileScan', 'FileSearch', 'FileSliders', 'FileSignal', 'FileSpreadsheet', 'FileStack', 'FileSymlink', 'FileTerminal',
  'FileText', 'FileType', 'FileTypeCorner', 'FileUp', 'FileUser', 'FileVideoCamera', 'FileVolume', 'FileXCorner',
  'File', 'Files', 'FileX', 'Film', 'FingerprintPattern', 'FireExtinguisher', 'FishOff', 'FishSymbol',
  'Fish', 'FishingHook', 'FishingRod', 'FlagOff', 'FlagTriangleLeft', 'FlagTriangleRight', 'Flag', 'FlameKindling',
  'Flame', 'Flashlight', 'FlashlightOff', 'FlaskConicalOff', 'FlaskConical', 'FlaskRound', 'FlipHorizontal2', 'FlipVertical2',
  'Flower2', 'Flower', 'Focus', 'FoldVertical', 'FoldHorizontal', 'FolderCheck', 'FolderArchive', 'FolderBookmark',
  'FolderClock', 'FolderCode', 'FolderClosed', 'FolderCog', 'FolderDot', 'FolderDown', 'FolderGit2', 'FolderHeart',
  'FolderGit', 'FolderInput', 'FolderKanban', 'FolderKey', 'FolderLock', 'FolderMinus', 'FolderOpenDot', 'FolderOpen',
  'FolderPen', 'FolderOutput', 'FolderPlus', 'FolderRoot', 'FolderSearch2', 'FolderSearch', 'FolderSymlink', 'FolderSync',
  'FolderTree', 'FolderUp', 'FolderX', 'Folder', 'Folders', 'Footprints', 'Forklift', 'Form',
  'Forward', 'Frame', 'Fuel', 'Fullscreen', 'FunnelPlus', 'FunnelX', 'Funnel', 'Galaxy',
  'GalleryHorizontal', 'GalleryHorizontalEnd', 'GalleryThumbnails', 'GalleryVerticalEnd', 'GalleryVertical', 'Gamepad2', 'GamepadDirectional', 'Gamepad',
  'Gavel', 'Gauge', 'Gem', 'GeorgianLari', 'Ghost', 'Gift', 'GitBranchMinus', 'GitBranchPlus',
  'GitBranch', 'GitCommitHorizontal', 'GitCommitVertical', 'GitCompareArrows', 'GitCompare', 'GitFork', 'GitGraph', 'GitMergeConflict',
  'GitMerge', 'GitPullRequestArrow', 'GitPullRequestClosed', 'GitPullRequestCreateArrow', 'GitPullRequestCreate', 'GitPullRequestDraft', 'GitPullRequest', 'GlassWater',
  'Glasses', 'GlobeCheck', 'GlobeLock', 'GlobeX', 'GlobeOff', 'Globe', 'Goal', 'Gpu',
  'GraduationCap', 'Grape', 'Grid2x2Check', 'Grid2x2Plus', 'Grid2x2X', 'Grid2x2', 'GripHorizontal', 'Grid3x2',
  'Grid3x3', 'GripVertical', 'Grip', 'Group', 'Ham', 'Guitar', 'Hamburger', 'HandCoins',
  'Hammer', 'HandFist', 'HandGrab', 'HandHeart', 'HandHelping', 'HandMetal', 'HandPlatter', 'Hand',
  'Handbag', 'Handshake', 'HardDriveDownload', 'HardDriveUpload', 'HardDrive', 'HardHat', 'Hash', 'Haze',
  'Hd', 'HatGlasses', 'HdmiPort', 'Heading2', 'Heading1', 'Heading3', 'Heading4', 'Heading5',
  'Heading6', 'Heading', 'HeadphoneOff', 'Headphones', 'HeartCrack', 'Headset', 'HeartHandshake', 'HeartMinus',
  'HeartPlus', 'HeartOff', 'HeartPulse', 'HeartX', 'Heart', 'Heater', 'Helicopter', 'Hexagon',
  'Highlighter', 'HopOff', 'Hop', 'Hospital', 'Hotel', 'Hourglass', 'HouseHeart', 'HousePlug',
  'HousePlus', 'HouseWifi', 'House', 'IceCreamBowl', 'IceCreamCone', 'IdCardLanyard', 'ImageDown', 'IdCard',
  'ImageMinus', 'ImageOff', 'ImagePlay', 'ImagePlus', 'ImageUp', 'ImageUpscale', 'Image', 'Images',
  'Import', 'Inbox', 'IndianRupee', 'Infinity', 'Info', 'InspectionPanel', 'Italic', 'IterationCcw',
  'IterationCw', 'Joystick', 'JapaneseYen', 'Kanban', 'Kayak', 'KeySquare', 'KeyRound', 'Key',
  'KeyboardMusic', 'KeyboardOff', 'Keyboard', 'LampCeiling', 'LampDesk', 'LampFloor', 'LampWallDown', 'LampWallUp',
  'LandPlot', 'Lamp', 'Landmark', 'Languages', 'LaptopMinimalCheck', 'LaptopMinimal', 'Laptop', 'LassoSelect',
  'Lasso', 'LayerArrowDown', 'LayerArrowUp', 'Layers2', 'LayersArrowDown', 'LayersArrowUp', 'LayersMinus', 'LayersPlus',
  'Layers', 'LayoutDashboard', 'LayoutFreeform', 'LayoutGrid', 'LayoutList', 'LayoutPanelTop', 'LayoutPanelLeft', 'Leaf',
  'LayoutTemplate', 'LeafyGreen', 'Lectern', 'LensConvex', 'LensConcave', 'LibraryBig', 'Library', 'LifeBuoy',
  'Ligature', 'LightbulbOff', 'Lightbulb', 'LineSquiggle', 'LineStyle', 'LineDotRightHorizontal', 'Link2Off', 'Link2',
  'Link', 'ListCheck', 'ListChecks', 'ListChevronsDownUp', 'ListChevronsUpDown', 'ListClock', 'ListCollapse', 'ListEnd',
  'ListFilterPlus', 'ListFilter', 'ListIndentIncrease', 'ListIndentDecrease', 'ListMinus', 'ListOrdered', 'ListMusic', 'ListPlus',
  'ListRestart', 'ListSortAscending', 'ListSortDescending', 'ListStart', 'ListTodo', 'ListTree', 'ListVideo', 'ListX',
  'List', 'LoaderCircle', 'LoaderPinwheel', 'LocateFixed', 'Loader', 'LocateOff', 'Locate', 'LockKeyholeOpen',
  'LockKeyhole', 'LockOpen', 'Lock', 'LogIn', 'LogOut', 'Logs', 'Lollipop', 'Luggage',
  'MailBadge', 'Magnet', 'MailCheck', 'MailClock', 'MailMinus', 'MailOpen', 'MailPlus', 'MailQuestionMark',
  'MailSearch', 'MailWarning', 'MailX', 'Mailbox', 'Mails', 'Mail', 'MapMinus', 'MapPinCheckInside',
  'MapPinCheck', 'MapPinHouse', 'MapPinMinusInside', 'MapPinMinus', 'MapPinOff', 'MapPinPen', 'MapPinPlusInside', 'MapPinPlus',
  'MapPinSearch', 'MapPinXInside', 'MapPinX', 'MapPlus', 'MapPin', 'MapPinned', 'Map', 'MarsStroke',
  'Mars', 'Martini', 'Maximize2', 'Maximize', 'MegaphoneOff', 'Medal', 'Megaphone', 'MemoryStick',
  'Menu', 'Merge', 'MessageCircleCheck', 'MessageCircleCode', 'MessageCircleDashed', 'MessageCircleHeart', 'MessageCircleMore', 'MessageCircleOff',
  'MessageCirclePlus', 'MessageCircleQuestionMark', 'MessageCircleReply', 'MessageCircleWarning', 'MessageCircleX', 'MessageCircle', 'MessageSquareCheck', 'MessageSquareCode',
  'MessageSquareDashed', 'MessageSquareDiff', 'MessageSquareDot', 'MessageSquareLock', 'MessageSquareHeart', 'MessageSquareMore', 'MessageSquareOff', 'MessageSquarePlus',
  'MessageSquareQuote', 'MessageSquareReply', 'MessageSquareShare', 'MessageSquareText', 'MessageSquareWarning', 'MessageSquareX', 'MessagesSquare', 'MessageSquare',
  'Metronome', 'MicAudioLines', 'MicOff', 'MicSignal', 'MicVocal', 'Mic', 'Microchip', 'Microwave',
  'Microscope', 'MidiPort', 'Milestone', 'Milk', 'MilkOff', 'Minimize2', 'Minimize', 'MirrorRound',
  'Minus', 'MirrorRectangular', 'MonitorCheck', 'MonitorCloud', 'MonitorCog', 'MonitorDot', 'MonitorDown', 'MonitorOff',
  'MonitorPause', 'MonitorPlay', 'MonitorSmartphone', 'MonitorSpeaker', 'MonitorStop', 'MonitorUp', 'MonitorX', 'Monitor',
  'MoonStar', 'Moon', 'MopSparkles', 'Mop', 'Mosque', 'Motorbike', 'MountainSnow', 'Mountain',
  'MouseLeft', 'MousePointer2Off', 'MouseOff', 'MousePointer2', 'MousePointerBan', 'MousePointerClick', 'MousePointer', 'MouseRight',
  'Mouse', 'Move3d', 'MoveDiagonal2', 'MoveDiagonal', 'MoveDownLeft', 'MoveDownRight', 'MoveDown', 'MoveHorizontal',
  'MoveLeft', 'MoveRight', 'MoveUpLeft', 'MoveUpRight', 'MoveUp', 'MoveVertical', 'Move', 'Music2',
  'Music3', 'Music', 'Music4', 'Navigation2Off', 'Navigation2', 'NavigationOff', 'Navigation', 'Network',
  'Newspaper', 'Nfc', 'NotebookPen', 'NonBinary', 'NotebookTabs', 'NotebookText', 'NotepadTextDashed', 'Notebook',
  'NotepadText', 'NutOff', 'OctagonAlert', 'OctagonMinus', 'Nut', 'OctagonPause', 'OctagonX', 'Octagon',
  'Omega', 'Option', 'Orbit', 'Origami', 'Package2', 'PackageMinus', 'PackageCheck', 'PackageOpen',
  'PackagePlus', 'PackageSearch', 'PackageX', 'Package', 'PaintBucket', 'PaintRoller', 'PaintbrushVertical', 'Paintbrush',
  'Palette', 'Panda', 'PanelBottomClose', 'PanelBottomDashed', 'PanelBottomOpen', 'PanelBottom', 'PanelLeftClose', 'PanelLeftDashed',
  'PanelLeftOpen', 'PanelLeftRightDashed', 'PanelLeft', 'PanelRightClose', 'PanelRightDashed', 'PanelRightOpen', 'PanelRight', 'PanelTopBottomDashed',
  'PanelTopClose', 'PanelTopDashed', 'PanelTop', 'PanelTopOpen', 'PanelsLeftBottom', 'PanelsRightBottom', 'PanelsTopLeft', 'PaperBag',
  'Paperclip', 'Parasol', 'Parentheses', 'ParkingMeter', 'PartyPopper', 'Pause', 'PawPrint', 'PenLine',
  'PcCase', 'PenOff', 'PenTool', 'Pen', 'PencilLine', 'PencilOff', 'PencilRuler', 'Pencil',
  'PencilSparkles', 'Pentagon', 'Percent', 'PersonStanding', 'Phi', 'PhilippinePeso', 'PhoneCall', 'PhoneForwarded',
  'PhoneIncoming', 'PhoneMissed', 'PhoneOutgoing', 'PhoneOff', 'Phone', 'Pi', 'Piano', 'Pickaxe',
  'PictureInPicture2', 'PictureInPicture', 'PiggyBank', 'PilcrowLeft', 'PilcrowRight', 'Pilcrow', 'PillBottle', 'Pill',
  'PinOff', 'Pin', 'Pipette', 'Pizza', 'PlaneLanding', 'PlaneTakeoff', 'Plane', 'PlayOff',
  'Play', 'Plug2', 'PlugZap', 'Plug', 'Plus', 'PocketKnife', 'Podium', 'PointerOff',
  'Pointer', 'Popcorn', 'Popsicle', 'PoundSterling', 'PowerOff', 'Power', 'Presentation', 'PrinterX',
  'PrinterCheck', 'Printer', 'Projector', 'Proportions', 'Puzzle', 'Pyramid', 'QrCode', 'Quote',
  'Rabbit', 'Radiation', 'Radar', 'Radical', 'RadioOff', 'RadioReceiver', 'RadioTower', 'Radio',
  'Radius', 'Rainbow', 'Rat', 'Ratio', 'ReceiptCent', 'ReceiptEuro', 'ReceiptJapaneseYen', 'ReceiptPoundSterling',
  'ReceiptIndianRupee', 'ReceiptRussianRuble', 'ReceiptSwissFranc', 'ReceiptText', 'ReceiptTurkishLira', 'Receipt', 'RectangleCircle', 'RectangleEllipsis',
  'RectangleGoggles', 'RectangleHorizontal', 'RectangleVertical', 'Recycle', 'Redo2', 'Redo', 'RedoDot', 'RefreshCcwDot',
  'RefreshCcw', 'RefreshCwOff', 'RefreshCw', 'Refrigerator', 'Regex', 'RemoveFormatting', 'Repeat2', 'Repeat1',
  'RepeatOff', 'Repeat', 'ReplaceAll', 'Replace', 'ReplyAll', 'Rewind', 'Ribbon', 'Reply',
  'Road', 'RobotArm', 'Rocket', 'RollerCoaster', 'RockingChair', 'Rose', 'Rotate3d', 'RotateCcwClock',
  'RotateCcwKey', 'RotateCcwSquare', 'RotateCcw', 'RotateCwFadingClock', 'RotateCwSquare', 'RotateCw', 'RouteOff', 'Route',
  'Router', 'Rows2', 'Rows3', 'Rows4', 'Rss', 'RulerDimensionLine', 'Ruler', 'RussianRuble',
  'Sailboat', 'Salad', 'Sandwich', 'SatelliteDish', 'Satellite', 'SaudiRiyal', 'SaveCheck', 'SaveAll',
  'SaveOff', 'SavePen', 'SavePlus', 'Save', 'Scale3d', 'Scale', 'Scaling', 'ScanBarcode',
  'ScanBox', 'ScanEye', 'ScanHeart', 'ScanFace', 'ScanQrCode', 'ScanLine', 'ScanSearch', 'ScanSquare',
  'ScanText', 'Scan', 'School', 'ScissorsLineDashed', 'Scissors', 'Scooter', 'ScreenShareOff', 'ScreenShare',
  'Scroll', 'SearchAlert', 'ScrollText', 'SearchCheck', 'SearchSlash', 'SearchCode', 'SearchX', 'Search',
  'SendHorizontal', 'Section', 'SendToBack', 'Send', 'SeparatorVertical', 'SeparatorHorizontal', 'ServerCog', 'ServerCrash',
  'ServerOff', 'ServerPlus', 'Server', 'Settings', 'Settings2', 'Shapes', 'Share2', 'Share',
  'Sheet', 'Shell', 'ShelvingUnit', 'ShieldAlert', 'ShieldBan', 'ShieldCheck', 'ShieldCogCorner', 'ShieldCog',
  'ShieldHalf', 'ShieldEllipsis', 'ShieldKeyhole', 'ShieldLock', 'ShieldMinus', 'ShieldOff', 'ShieldPlus', 'ShieldQuestionMark',
  'ShieldUser', 'ShieldX', 'Shield', 'ShipCargo', 'ShipWheel', 'Ship', 'Shirt', 'ShoppingBasket',
  'ShoppingCart', 'ShoppingBag', 'Shovel', 'ShowerHead', 'Shrimp', 'Shredder', 'Shrink', 'Shrub',
  'Shuffle', 'Sigma', 'SignalHigh', 'SignalLow', 'SignalMedium', 'SignalZero', 'Signal', 'Signature',
  'SignpostBig', 'Signpost', 'Siren', 'SkipForward', 'SkipBack', 'Skull', 'Slice', 'Slash',
  'SlidersHorizontal', 'SlidersVertical', 'SmartphoneCharging', 'SmartphoneNfc', 'Smartphone', 'Snail', 'Snowflake', 'SoapDispenserDroplet',
  'Sofa', 'SolarPanel', 'Soup', 'Space', 'Spade', 'Sparkle', 'Sparkles', 'Speaker',
  'Speech', 'SpellCheck2', 'SpellCheck', 'SplinePointer', 'Spline', 'Split', 'Spool', 'SportShoe',
  'SprayCan', 'Spotlight', 'Sprout', 'SquareActivity', 'SquareArrowDownLeft', 'SquareArrowDownRight', 'SquareArrowDown', 'SquareArrowLeft',
  'SquareArrowOutDownLeft', 'SquareArrowOutUpLeft', 'SquareArrowOutDownRight', 'SquareArrowRightExit', 'SquareArrowOutUpRight', 'SquareArrowRightEnter', 'SquareArrowUpLeft', 'SquareArrowRight',
  'SquareArrowUpRight', 'SquareArrowUp', 'SquareAsterisk', 'SquareBottomDashedScissors', 'SquareCenterlineDashedHorizontal', 'SquareCenterlineDashedVertical', 'SquareChartGantt', 'SquareCheckBig',
  'SquareCheck', 'SquareChevronDown', 'SquareChevronLeft', 'SquareChevronRight', 'SquareChevronUp', 'SquareCode', 'SquareDashedBottomCode', 'SquareDashedBottom',
  'SquareDashedKanban', 'SquareDashedMousePointer', 'SquareDashedText', 'SquareDashedTopSolid', 'SquareDashed', 'SquareDimensions', 'SquareDivide', 'SquareEqual',
  'SquareDot', 'SquareFunction', 'SquareKanban', 'SquareLibrary', 'SquareM', 'SquareMenu', 'SquareMinus', 'SquareMousePointer',
  'SquareOff', 'SquareParkingOff', 'SquareParking', 'SquarePause', 'SquarePen', 'SquarePercent', 'SquarePi', 'SquarePilcrow',
  'SquarePlay', 'SquarePlus', 'SquarePower', 'SquareRoundCorner', 'SquareRadical', 'SquareScissors', 'SquareSigma', 'SquareSlash',
  'SquareSplitHorizontal', 'SquareSplitVertical', 'SquareSquare', 'SquareStack', 'SquareStar', 'SquareStop', 'SquareTerminal', 'SquareText',
  'SquareUserRound', 'SquareUser', 'SquareX', 'Square', 'SquaresExclude', 'SquaresSubtract', 'SquaresUnite', 'SquaresIntersect',
  'SquircleDashed', 'Squircle', 'Stamp', 'Squirrel', 'StarCheck', 'StarHalf', 'StarMinus', 'StarOff',
  'StarPlus', 'StarX', 'StepBack', 'Star', 'StepForward', 'Stethoscope', 'Sticker', 'StickyNoteCheck',
  'StickyNoteOff', 'StickyNoteMinus', 'StickyNotePlus', 'StickyNoteX', 'StickyNotes', 'StickyNote', 'Stone', 'Store',
  'StretchHorizontal', 'Strikethrough', 'StretchVertical', 'Subscript', 'Summary', 'SunDim', 'SunMedium', 'SunMoon',
  'SunSnow', 'Sun', 'Sunrise', 'Sunset', 'Superscript', 'SwatchBook', 'SwissFranc', 'SwitchCamera',
  'Sword', 'Swords', 'Syringe', 'Table2', 'TableCellsMerge', 'TableCellsSplit', 'TableColumnsSplit', 'TableOfContents',
  'TableProperties', 'TableRowsSplit', 'Table', 'TabletSmartphone', 'Tablet', 'Tablets', 'TagPlus', 'Tag',
  'Tags', 'TagX', 'Tally1', 'Tally2', 'Tally3', 'Tally4', 'Tally5', 'Tangent',
  'Target', 'Telescope', 'TentTree', 'Terminal', 'Tent', 'TestTubeDiagonal', 'TestTube', 'TestTubes',
  'TextAlignCenter', 'TextAlignEnd', 'TextAlignJustify', 'TextAlignStart', 'TextCursorInput', 'TextCursor', 'TextInitial', 'TextQuote',
  'TextSearch', 'TextWrap', 'Theater', 'ThermometerSnowflake', 'ThermometerSun', 'Thermometer', 'ThumbsDown', 'ThumbsUp',
  'TicketCheck', 'TicketMinus', 'TicketPercent', 'TicketPlus', 'TicketSlash', 'TicketX', 'Ticket', 'TicketsPlane',
  'Tickets', 'Timeline', 'TimerOff', 'TimerReset', 'ToggleLeft', 'Timer', 'ToggleRight', 'ToolCase',
  'Toilet', 'Toolbox', 'Tornado', 'Torus', 'TouchpadOff', 'Touchpad', 'TowelRack', 'TowerControl',
  'ToyBrick', 'Tractor', 'TrafficCone', 'Trailer', 'TrainFront', 'TrainFrontTunnel', 'TrainTrack', 'TramFront',
  'Transgender', 'Trash2', 'Trash', 'TreeDeciduous', 'TreePalm', 'TreePine', 'Trees', 'TrendingDown',
  'TrendingUpDown', 'TrendingUp', 'TriangleAlert', 'TriangleDashed', 'TriangleRight', 'Triangle', 'Trophy', 'TruckElectric',
  'Truck', 'TurkishLira', 'Turntable', 'Turtle', 'TvMinimalPlay', 'TvMinimal', 'Tv', 'TypeOutline',
  'Type', 'UmbrellaOff', 'Umbrella', 'Underline', 'Undo2', 'UndoDot', 'Undo', 'UnfoldHorizontal',
  'UnfoldVertical', 'Ungroup', 'University', 'Unlink2', 'Unlink', 'Unplug', 'Upload', 'UsbCPort',
  'Usb', 'UserCheck', 'UserCog', 'UserKey', 'UserLock', 'UserMinus', 'UserPen', 'UserPlus',
  'UserRoundArrowLeft', 'UserRoundCheck', 'UserRoundCog', 'UserRoundKey', 'UserRoundMinus', 'UserRoundPen', 'UserRoundPlus', 'UserRoundSearch',
  'UserRoundX', 'UserRound', 'UserSearch', 'UserShield', 'UserStar', 'UserX', 'User', 'UsersRound',
  'Users', 'UtensilsCrossed', 'Utensils', 'UtilityPole', 'Van', 'Vault', 'Variable', 'VectorSquare',
  'Vegan', 'VenetianMask', 'VenusAndMars', 'Venus', 'VibrateOff', 'Vibrate', 'VideoOff', 'Video',
  'Videotape', 'View', 'Voicemail', 'Volleyball', 'Volume1', 'Volume2', 'VolumeOff', 'VolumeX',
  'Volume', 'Vote', 'WalletCards', 'WalletMinimal', 'Wallet', 'Wallpaper', 'WandSparkles', 'Wand',
  'WashingMachine', 'Warehouse', 'Watch', 'WavesArrowUp', 'WavesArrowDown', 'WavesHorizontal', 'WavesLadder', 'WavesVertical',
  'Waypoints', 'WebcamOff', 'Webcam', 'WebhookOff', 'Webhook', 'WeightTilde', 'Weight', 'WheatOff',
  'Wheat', 'WholeWord', 'WifiCog', 'WifiHigh', 'WifiLow', 'WifiOff', 'WifiPen', 'WifiSync',
  'WifiZero', 'Wifi', 'WindArrowDown', 'Wind', 'WineOff', 'Workflow', 'Wine', 'Worm',
  'WrenchOff', 'Wrench', 'XLineTop', 'X', 'ZapOff', 'Zap', 'ZodiacAquarius', 'ZodiacAries',
  'ZodiacCancer', 'ZodiacGemini', 'ZodiacCapricorn', 'ZodiacLeo', 'ZodiacLibra', 'ZodiacOphiuchus', 'ZodiacPisces', 'ZodiacSagittarius',
  'ZodiacScorpio', 'ZodiacVirgo', 'ZodiacTaurus', 'ZoomIn', 'ZoomOut'
]

export const MODULE_ICON_KEY_SET: ReadonlySet<string> = new Set(MODULE_ICON_KEYS)

export type ModuleIconKey = string
